name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.9.4
        otp-version: 22.2

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: mix deps.get
    - name: Check format
      run: mix format --check-formatted
    - name: Run Tests
      run: mix coveralls.github
